//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teveguide.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeveGuideEntities : DbContext
    {
        public TeveGuideEntities()
            : base("name=TeveGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tv_shows> tv_shows { get; set; }
        public virtual DbSet<users> users { get; set; }

        public System.Data.Entity.DbSet<teveguide.Models.TvShow> TvShows { get; set; }
    }
}
